/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GeodetikaRouteImport } from './routes/geodetika'
import { Route as IndexRouteImport } from './routes/index'

const GeodetikaRoute = GeodetikaRouteImport.update({
  id: '/geodetika',
  path: '/geodetika',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/geodetika': typeof GeodetikaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/geodetika': typeof GeodetikaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/geodetika': typeof GeodetikaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/geodetika'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/geodetika'
  id: '__root__' | '/' | '/geodetika'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GeodetikaRoute: typeof GeodetikaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/geodetika': {
      id: '/geodetika'
      path: '/geodetika'
      fullPath: '/geodetika'
      preLoaderRoute: typeof GeodetikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GeodetikaRoute: GeodetikaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
