/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GeodezieRouteImport } from './routes/geodezie'
import { Route as IndexRouteImport } from './routes/index'

const GeodezieRoute = GeodezieRouteImport.update({
  id: '/geodezie',
  path: '/geodezie',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/geodezie': typeof GeodezieRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/geodezie': typeof GeodezieRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/geodezie': typeof GeodezieRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/geodezie'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/geodezie'
  id: '__root__' | '/' | '/geodezie'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GeodezieRoute: typeof GeodezieRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/geodezie': {
      id: '/geodezie'
      path: '/geodezie'
      fullPath: '/geodezie'
      preLoaderRoute: typeof GeodezieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GeodezieRoute: GeodezieRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
